services:
  wb-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ""
    image: wb-web:latest
    container_name: wb-web
    ports:
      - "80:80"
    networks:
      - container_test
    restart: unless-stopped

networks:
  container_test:
    external: true
